<?php
/**
 * @file
 * Code for the GSB Feature Image FPP feature.
 */

include_once 'gsb_feature_image_fpp.features.inc';
/**
 * @file
 * Code for the GSB Feature Image FPP feature.
 */

/**
 * Implements hook_entity_alter().
 */
function gsb_feature_image_fpp_entity_info_alter(&$entity_info) {
  $entity_info['fieldable_panels_pane']['bundles']['image'] = array(
    'label' => t('Image'),
    'pane category' => t('GSB panes'),
    'pane top level' => TRUE, // set to true to make this show as a top level icon
    'pane icon' => drupal_get_path('module', 'panopoly_widgets') . '/images/icon_image_fpp.png',
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      // Note that this has all _ replaced with - from the bundle name.
      'real path' => 'admin/structure/fieldable-panels-panes/manage/image',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}

/**
 * Implements hook_form_alter()
 */
function gsb_feature_image_fpp_form_alter(&$form, &$form_state, $form_id) {

  if ($form_id == 'fieldable_panels_panes_fieldable_panels_pane_content_type_edit_form' && $form['#bundle'] == 'image') {

    $form['#after_build'][] = 'gsb_feature_image_fpp_edit_button_form_alter';

  }

}

function gsb_feature_image_fpp_edit_button_form_alter($form) {
  $language = $form['language']['#value'];
  $form['field_file_single_public'][$language][0]['edit']['#access'] = false;
  return $form;
}
